<?php


use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\node\NodeStorageInterface;


function wedding_theme_page_attachments_alter(&$attachments) {
    if (\Drupal::service('path.matcher')->isFrontPage()) {
        $attachments['#attached']['library'][] = 'wedding_theme/home-page';
    }
    // Not entirely sure but this has to be here. Might fix the webform problem
    $attachments['#attached']['library'][] = 'wedding_theme/slick';
}